baseURL = "https://sage-hamburg.github.io/"
languageCode = "de-de"
title = "SAGE Hamburg"
theme = "no-js-hugo-theme"
googleAnalytics = ""

[params]
    # siehe https://github.com/stevenengler/no-js-hugo-theme/blob/master/exampleSite/config.toml
    themeStyleSwitcher = true # default false
    footerText = "Source: [github.com/sage-hamburg](https://github.com/SAGE-Hamburg/sage-hamburg.github.io) . &nbsp;Made with Hugo + [no-js-hugo-theme](https://github.com/stevenengler/no-js-hugo-theme)"
    tocWordThreshold = 1000



[markup]
  [markup.highlight]
    codeFences = true
    noClasses = false

  [markup.tableOfContents]
    startLevel = 1
    endLevel = 6

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

# "uns" gibt es noch nicht
#[[menu.main]]
#    url = "/about/"
#    name = "Über uns"
#    weight = 2

[[menu.main]]
    url = "/aktuelles/"
    name = "Aktuelles"
    weight = 2

[[menu.main]]
    url = "/historisch/"
    name = "Historisches"
    weight = 3


# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.

# Das ist aus dem alten Theme... wäre aber ganz schön inkl. meetup zu haben

[[menu.icon]]
    url = "mailto:hamburg@guug.de"
    name = "fas fa-envelope"
    weight = 1

[[menu.icon]]
    url = "https://github.com/sage-hamburg/"
    name = "fab fa-github"
    weight = 2

[[menu.icon]]
    url = "https://twitter.com/username/"
    name = "fab fa-twitter"
    weight = 3
